# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ati_id', models.CharField(max_length=400)),
                ('load_city', models.CharField(max_length=400)),
                ('unload_city', models.CharField(max_length=400)),
                ('cargo_name', models.CharField(max_length=400)),
                ('cargo_weight', models.FloatField()),
                ('cargo_volume', models.FloatField()),
            ],
        ),
    ]
