# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loads',
            name='cargo_name',
        ),
        migrations.RemoveField(
            model_name='loads',
            name='cargo_volume',
        ),
        migrations.RemoveField(
            model_name='loads',
            name='cargo_weight',
        ),
        migrations.RemoveField(
            model_name='loads',
            name='load_city',
        ),
        migrations.RemoveField(
            model_name='loads',
            name='unload_city',
        ),
        migrations.AddField(
            model_name='loads',
            name='add_date',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='firm_city',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='firm_contacts',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='firm_fullname',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='firm_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='firm_profile',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='load_cargo_type',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='load_volume',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='load_weight',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='loading_city',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='loading_region',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='rate_currency',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='rate_price_nds',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='rate_price_nonds',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='route_distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='truck_car_types',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='truck_loading_types',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='truck_unloading_types',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='unloading_city',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='unloading_region',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='loads',
            name='ati_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
