# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_auto_20190409_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='loads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2019-04-09T18:00:00'),
            preserve_default=False,
        ),
    ]
