# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0003_loads_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loads',
            name='created_at',
        ),
    ]
