# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0004_remove_loads_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
