# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0006_auto_20190412_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('started', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished', models.FloatField(blank=True, default=None, null=True)),
                ('combinations_done', models.FloatField(blank=True, default=None, null=True)),
                ('combinations_left', models.FloatField(blank=True, default=None, null=True)),
                ('parsed_total', models.FloatField(blank=True, default=None, null=True)),
                ('created_total', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
