# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0008_loads_full_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='loads',
            name='firm_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='parser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse.Parser'),
        ),
    ]
